### ISSUE TITLE
Replace all contributor role names with ids (config.json)

### ISSUE THREAD

**Issue by Glup3** [anomalilies/Nira-chan#64]
```
original:

"contributorRole": [
    "Journalists",
    "Contestants",
    "Hackers",
    "Stans",
    "Editors",
    "Translators",
    "Meme Royalty",
    "Theorists",
    "Musicians",
    "Artists"
  ]

use this:

"allContributorRoles": [
    "765670343934345277",
    "770792091353743401",
    "812427932512813077",
    "769728601036947467",
    "742066260811972709",
    "742061295255289859",
    "742061039532638278",
    "751205513806610454",
    "756314524285534259",
    "758774148154523669",
    "758774087161741363"
  ]
```

**Comment by jukiforde** [comment]
Hey @Glup3,

I would like to help out on this, but I will need some more information as I cannot seem to find any contributer roles in the *config.json* file as indicated.

The closest thing I see to `"contributorRole": [` or `"allContributorRoles": [`  is the below: 

```JSON

        "contributionchannels": [
            "735658144646168697",
            "603248096607993866",
            "603248158088101929",
            "761326959154167838",
            "747207562277158934",
            "758492257543913502"
        ],
```
Not sure if I am missing something, would greatly appreciate your feedback.

**Comment by Glup3** [comment]
Hey @jukiforde!

Sorry for the late response, I just saw it.
We are currently porting Nira-chan to Typescript and it will be Nira-chan 2.0.
You are using the master branch, which is still the "old" Nira-chan.
All the Issues are for the branch "typescript"
